FROM ubuntu:18.04

WORKDIR /crime-analytics
RUN mkdir /crime-analytics/backend
RUN mkdir /crime-analytics/frontend

RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN apt-get install -y nginx

COPY ./backend/package*.json /crime-analytics/backend/
COPY ./frontend/package*.json /crime-analytics/frontend/

WORKDIR /crime-analytics/backend
RUN npm install

WORKDIR /crime-analytics/frontend
RUN npm install

COPY ./backend /crime-analytics/backend
COPY ./frontend /crime-analytics/frontend

RUN npm run build
WORKDIR /crime-analytics/
COPY ./CICD/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000 12059

CMD ((nginx -g "daemon off;") & (cd /crime-analytics/backend/; npm run start))
