FROM ubuntu:18.04

WORKDIR /crime_analytics
RUN mkdir /data
RUN mkdir /crime_analytics/analytics

RUN apt-get update
RUN apt-get install -y python3
RUN apt-get -y install python3-pip
RUN pip3 install gunicorn


WORKDIR /crime_analytics/analytics
COPY ./analytics/requirements.txt /crime_analytics/analytics/requirements.txt
RUN pip3 install -r requirements.txt

COPY ./analytics /crime_analytics/analytics


EXPOSE 13000

CMD (gunicorn -b:13000 --timeout 18000 testAnalytics:api)
